### ISSUE TITLE
Sample site for webgen

### ISSUE THREAD

**Issue by gettalong** [staystatic/staystatic.github.io#1]
Hi,

you will find a sample [webgen](http://webgen.gettalong.org) website in the attached [webgen-static.zip](https://github.com/staystatic/staystatic.github.io/files/90864/webgen-static.zip).

The `out/` directory contains the generated output, the `src/` and `ext/` directories as well as the `webgen.config` file are part of the website source.

I have tried to make the site as close as possible to your existing Jekyll and Hugo ones.

Cheers
  Thomas

**Comment by geraldb** [comment]
Wow. Fantastic. Will add the repo and showcase / sample later today. Thanks again. Cheers.

**Comment by geraldb** [comment]
@gettalong  Thanks again webgen is now included, see the [/webgen](https://github.com/staystatic/webgen) repo and [/sites/webgen](http://staystatic.github.io/sites/webgen)  Cheers.
